esphome:
  name: "elcentral-garage"

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.42
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

web_server:
  port: 80

sensor:
  - platform: dht
    model: DHT22
    pin:
      # GND: green/white
      # VCC: orange
      # DATA: green
      number: D2
      mode: INPUT_PULLUP
    temperature:
      name: "garage_temperature"
    humidity:
      name: "garage_humidity"
    update_interval: 60s

  - platform: pulse_meter
    name: "zap_tec"
    pin:
      # red/brown
      number: D3
      mode: INPUT_PULLUP
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
