esphome:
  name: "elcentral"

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.92
    gateway: 192.168.0.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

logger:

# Enable Home Assistant API
api:

mqtt:
  broker: 192.168.0.5
  port: 1883
  username: !secret mqtt_user
  password: !secret mqtt_password

ota:

web_server:
  port: 80

sensor:
  # SDM120D
  # Pull down 10K
  # +  ---- 5V
  # -  ---- GPIOx
  #      |--- || --- GND
  #          10K

  - platform: dht
    model: DHT22
    pin:
      number: D2
      mode: INPUT_PULLUP
    temperature:
      name: "cold_cellar_temperature"
    humidity:
      name: "cold_cellar_humidity"
    update_interval: 60s

  - platform: pulse_meter
    name: "heat_pump"
    pin:
      # Orange/white
      number: D3
      mode: INPUT_PULLUP
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: pulse_meter
    name: "ev_charger"
    pin:
      # Green/white
      number: D4
      mode: INPUT_PULLUP
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: pulse_meter
    name: "freezer"
    # Purple/white
    pin: D6
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: pulse_meter
    name: "fridge"
    # Brown/white
    pin: D5
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: pulse_meter
    name: "washer"
    # Blue/white
    pin: D7
    unit_of_measurement: "W"
    device_class: "power"
    internal_filter: 100ms
    accuracy_decimals: 3
    timeout: 2 min
    filters:
      - multiply: 60

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
